name: VoiceInput
options:
  bundleIdPrefix: com.voiceinput
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: SmartVoiceIn
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES

packages:
  Qwen3ASR:
    url: https://github.com/ivan-digital/qwen3-asr-swift.git
    revision: cc41cddc5dc9cd61fd069d3581cac8e4e03425c0
  MLXSwiftLM:
    url: https://github.com/ml-explore/mlx-swift-lm.git
    from: 2.29.1

targets:
  VoiceInput:
    productName: SmartVoiceIn
    type: application
    platform: macOS
    sources:
      - path: Sources
    resources:
      - path: Resources
    dependencies:
      - package: Qwen3ASR
      - package: MLXSwiftLM
        product: MLXLLM
      - package: MLXSwiftLM
        product: MLXLMCommon
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/VoiceInput.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceinput.app
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
    entitlements:
      path: Resources/VoiceInput.entitlements
